using System;
using Runtime.Core.Architecture.GameGlobalState.Contract;
using Runtime.Core.Architecture.GameGlobalState.States.App;
using Runtime.Core.Architecture.GameGlobalState.States.Gameplay;

namespace Runtime.Core.Architecture.GameGlobalState.Factor
{
/// <summary>
/// Default implementation of state factory that creates states with their dependencies.
/// This class is generated by your DI framework in real usage.
/// </summary>
public class StateFactory : IStateFactory
{
	public IState CreateState(string stateId)
	{
		switch (stateId)
		{
			case "app/bootstrap":
				return BootstrapStateFactory.CreateBootstrapState();
			case "app/mainmenu":
				return MainMenuStateFactory.CreateMainMenuState();
			case "app/gameplay":
				return GameplayStateFactory.CreateGameplayState();
			case "app/shutdown":
				return new ShutdownState();
			case "gameplay/city":
				return CityStateFactory.CreateCityState();
			case "gameplay/crypt":
				return CryptStateFactory.CreateCryptState();
			default:
				throw new Exception($"Unknown state type {stateId}. Maybe need to implement it in factory?");
		}
	}
}
}